spring.application.name=activityService

# db connection
spring.data.mongodb.uri=mongodb://localhost:27017/fitness_activity
spring.data.mongodb.database=fitness_activity


spring.server.port=8082

#mongodb://localhost:27017
