spring.application.name=userService

#JPA data
spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_user_db
spring.datasource.username=postgres
spring.datasource.password=75369

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
